### ISSUE TITLE
파이어폭스 최신버전 코드 하이라이팅 적용 안되는 증상

### ISSUE THREAD

**Issue by gustjd887** [pronist/hELLO#10]
파이어폭스 최신버전에서 코드 하이라이팅이 적용이 안되는 증상이 있습니다.
![image](https://user-images.githubusercontent.com/42667334/91663856-5d033f80-eb26-11ea-8cdc-f1e460283f2d.png)
아마 하이라이팅 적용되기 전의 텍스트로 출력되는 것 같습니다.

![image](https://user-images.githubusercontent.com/42667334/91663929-c08d6d00-eb26-11ea-830f-6701a2c7f1d3.png)
크롬은 정상 적용되며, 스마트폰이나 태블릿도 정상 적용됩니다.

테스트 페이지는 아래와 같습니다.
https://gustjd887.tistory.com/37

**Comment by pronist** [comment]
이 문제는 원인을 알아내었으며, 차기 버전에서 수정됩니다. 
버그를 신고해주셔서 감사합니다. :)
