### ISSUE TITLE
[버그] 우측 소제목 리스트 부분 Bold 처리 안되는 이슈

### ISSUE THREAD

**Issue by benny-coding** [pronist/hELLO#13]
안녕하세요~ hELLO님의 티스토리 스킨을 사용 중인 베니라고 합니다! 😄 
스킨 너무 좋고 잘 사용하고 있어서 감사드립니다! 🙇‍♂️ 

다름이 아니라 스킨을 사용하여 글을 작성하였는데 우측 소제목 부분이 스크롤을 내려도
Bold 처리가 되지 않는 이슈를 발견하였습니다~ 😱 

혹시 제 것만 그런 것인지 확인해보니 hELLO님 블로그의 PHP 최신 글도 같은 현상이 보여서 제보 드립니다! 🚨

**Comment by pronist** [comment]
제보해주셔서 감사합니다! 해당 문제는 다음 버전에서 해결될 예정입니다. :)
