### ISSUE TITLE
댓글/방명록 작성 로그인한 사용자만 처리(로그인 alert 두번 발생)

### ISSUE THREAD

**Issue by YuchanSong** [pronist/hello#222]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: macOS
- 브라우저: Chrome
- 버전: Sonoma 14.4.1
- 스킨 버전 : hELLO 4.2.2

**설명**
1. 댓글/방명록 작성시 로그인하겠냐는 confirm 창이 두번 뜸.
2. "확인" or "취소" 클릭해도 먹통인 증상이 있음 (esc로 탈출 가능)

**발생 과정**
1. 티스토리 관리자 페이지에서 로그인한 작성자만 댓글 혹은 방명록 작성 가능하게 설정
2. 로그아웃 상태에서 댓글 혹은 방명록 textarea 영역 클릭 (이때 confirm 발생)

**스크린샷 및 링크**
<img width="476" alt="image" src="https://github.com/pronist/hello/assets/30282985/64f019c8-fad6-4f3c-9e64-25efd1656d8d">
<img width="448" alt="image" src="https://github.com/pronist/hello/assets/30282985/6a28e1f4-879f-465b-8972-1390e1ff4c8d">

제 블로그에서 재현되고 있어서 링크 남깁니다
https://dvlpr-chan.tistory.com/guestbook

**Comment by pronist** [comment]
@YuchanSong 안녕하세요. 그 버그는 놀랍게도 제 코드가 아닌 티스토리의 레거시 코드에서 발생하고 있습니다. 카카오가 로드하는 스크립트 중에 **common.js** 라는게 있는데, 이벤트를 트래킹해서 호출 스택을 조사해보면 두 번의 사이클이 돌고 있습니다. 이는 티스토리의 새로운 댓글 시스템에서는 해당하지 않지만 레거시에서만 발생하는 문제입니다. 새로운 댓글 시스템은 디자인과 코드의 자유도 문제로 스킨에 반영하고 있지 않습니다만, 티스토리 측의 버그로 불행하게도 제가 해결이 불가능한 상황입니다. 

바보같은 티스토리는 버그가 참 많은 블로그 서비스네요. xD

![image](https://github.com/pronist/hello/assets/25624965/ef9197fd-6163-4c8f-b014-c42f19fe0231)

**Comment by YuchanSong** [comment]
@pronist 확인 감사합니다!! :)
