### ISSUE TITLE
화면 구성 관련 버그 문의드립니다!

### ISSUE THREAD

**Issue by Hyejinijini** [pronist/hello#225]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: windows10
- 브라우저: chrome
- 버전: 22
- 스킨 버전 (스킨 버전은 index.xml 에서 확인): 4.3.0

**설명**
버그가 어떻게 발생하는지 알려주세요. 대략적인 버그의 설명을 적어주시면 됩니다.
: 화면 중앙에 페이지 번호가 뜨고 클릭이 안됩니다.
그리고 글을 작성하면 원래 제목+본문이 같이 보였는데 오늘 업로드 한 글부터는 본문 내용이 보이지 않습니다.

**발생 과정**
버그가 어떤 과정을 통해 발생하는지 구체적으로 적어주세요.
: 04.30 오늘자로 글 작성 후, 완료 누르니까 갑자기 버그가 발생했습니다.
오늘 버그 발생하기 전까지 따로 HTML이나 CSS는 건드린 게 하나도 없었습니다.

**스크린샷 및 링크**
버그가 발생한 상황을 가능하다면 스크린샷을 첨부해주세요. 또한 버그가 발생한 모습이 있는 포스트의 주소를 첨부해주시는 것도 아주 좋습니다!
![버그](https://github.com/pronist/hello/assets/155633287/c7841198-0a3e-44e3-ba09-aeb9b8fb00af)
[https://hye-story-o0o.tistory.com/](url)

**Comment by pronist** [comment]
@Hyejinijini 안녕하세요. 해당 문제 또한 살펴보니 #224 과 결이 같은 것으로 파악되었습니다. 따라서 관련 이슈에서 함께 논의하면 될 것 같습니다.

![image](https://github.com/pronist/hello/assets/25624965/21802728-148a-4d2b-b748-686d1c3e87e5)
