### ISSUE TITLE
Firefox 브라우저에서 검색창 및 레이아웃 밀림오류

### ISSUE THREAD

**Issue by Cyp9715** [pronist/hello#227]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: Windows 11(22631.3447)
- 브라우저: Firefox 
- 버전: 126.0
- 스킨 버전: 4.2.2

**설명**
간단한 UI 버그입니다. 

![image](https://github.com/pronist/hello/assets/16573620/24e66531-f43c-4a34-bcb3-f16b00001ae8)

위 이미지와 같이 검색창이 제대로 표시되지 않으며,

![image](https://github.com/pronist/hello/assets/16573620/ea354221-66db-48cb-ae93-79a7ffcdccd0)

검색창에 많은 글자를 입력시 좌측의 카테고리 레이아웃 자체가 밀리는 현상이 발생합니다.  
오직 Firefox 브라우저에서만 발생하는 현상으로 호환성 문제인듯 합니다.  

외에 Chrome, Whale, Edge 등 Chromium 기반 브라우저에서는 문제 없이 잘 작동합니다.

**Comment by pronist** [comment]
@Cyp9715 안녕하세요. 

음, 그렇네요. 확인 완료되었습니다. 다음 버그픽스에 반영 될 겁니다. 

기여해주셔서 감사합니다.
