### ISSUE TITLE
글 삭제 시에도 메인 화면에서 글, 태그가 남아있는 현상

### ISSUE THREAD

**Issue by gulf1324** [pronist/hello#228]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: Windows11
- 브라우저: Chrome
- 버전: 125.0.6422.113(공식 빌드) (64비트)
- 스킨 버전 (스킨 버전은 index.xml 에서 확인): 4.5.2

**설명**    

1. 태그가 달린 글을 삭제해도 해당 태그들이 홈 화면 사이드바에 남아있는 현상  
2. 글을 지웠지만 메인 화면에 표시되는 현상

**발생 과정**
1. 글을 작성하고, 태그를 여러 개 달고, 글을 삭제했지만 여전히 홈 화면 태그 통계가 반영되고 있었습니다.   
2. 30분 이후에도 삭제한 글이 메인 화면에 여전히 남아있습니다. ( 클릭해서 들어가면 "권한이 없거나 존재하지 않는 글입니다" 라고 뜨긴 합니다.)

**조금 다른 두 개의 버그이지만 연관이 있는 것 같아서 묶어서 이슈 드립니다~**

**스크린샷 및 링크**
[https://gulf1324.tistory.com/](https://gulf1324.tistory.com/)

**Comment by pronist** [comment]
@gulf1324 안녕하세요. 그 두 버그는 티스토리 내부에서 발생하는 **티스토리 버그**입니다. 글을 삭제해도 일정 시간 남아있는 현상은 티스토리에서 버그가 발생하여 블로그에 반영이 늦게 되기 때문입니다. 저도 여러 번 겪은 바 있습니다. 이 문제는 플랫폼 문제이므로 스킨 차원에서 처리할 수 있는 일이 없습니다.

**Comment by gulf1324** [comment]
그렇군요 감사합니다!. 오늘 처음 해봤는데 스킨 좋네요 잘 쓰겠습니다 ㅎㅎ
