### ISSUE TITLE
특정 환경에서 스킨 로딩 불가능한 문제 제보

### ISSUE THREAD

**Issue by ninefloor** [pronist/hELLO#23]
깔끔하고 멋진 스킨 잘 사용하고 있습니다.

제가 블로그를 사용하는 환경이 집/학원인데, 집에선 문제가 없었으나 학원의 네트워크 문제인지 스킨의 로딩이 되지 않아 블로그 자체를 볼 수 없는 현상을 발견했습니다.

`<script src="//code.jquery.com/jquery-3.4.1.min.js"></script>`

확인해보니 이 부분에서 로딩이 제대로 되지 않아 발생하는 문제인 것으로 파악했고, 일단 다른 곳(cdnjs)에서 동일한 버전의 주소를 받아 입력하니 정상작동됩니다. 

웹 개발은 완전 초짜라 이게 정확한 해결 방법인지는 모르겠습니다만, 특정 환경에서 발생하는 문제가 있다는 점을 알려드리면 작게나마 도움이 될까싶어 제보드립니다. 늘 감사합니다!

**Comment by pronist** [comment]
이 문제를 네트워크 문제로 봐야할지, jQuery 소스가 있는 서버의 문제로 봐야할지는 다소 의문스럽군요. 
일단 바로 조치는 하지 않을 것 같지만, 알고는 있겠습니다. 

고맙습니다 :)

**Comment by ninefloor** [comment]
제 느낌으로는 제가 다니는 학원에서 특정 url의 반응속도가 현저히 느린 것이 사실입니다. 일반적인 환경에서는 문제가 없을 것이라 생각되고, 특정한 환경에서의 문제에 대해 알려드리는 게 차후 다른 문제 발생 시 어느정도 참고가 될 수 있을거라 생각하여 제보드린 것이니 이러한 케이스가 있다는 점만 양지해주셔도 충분합니다. 감사합니다 :)

**Comment by pronist** [comment]
이 부분, 일단은 퍼포먼스가 어느정도 일단락 되었습니다. :)
