### ISSUE TITLE
목차에서 키캡이모티콘이 깨지는 버그

### ISSUE THREAD

**Issue by ls2hn** [pronist/hello#234]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제:  windows
- 브라우저:  chrome
- 버전: 버전 126.0.6478.61(공식 빌드) (64비트)
- 스킨 버전 (스킨 버전은 index.xml 에서 확인): 4.2.2

**설명**
버그가 어떻게 발생하는지 알려주세요. 대략적인 버그의 설명을 적어주시면 됩니다.

키캡 이모티콘 ( e.g. 1️⃣2️⃣3️⃣4️⃣5️⃣6️⃣7️⃣8️⃣ ) 을 적으면 본문과 목차에 이모티콘이 온전히 나오지 않고 깨져서 나옵니다. 
다른 테마의 블로그 목차에는 제대로 나오는 걸 본 적이 있습니다.
글쓰기 화면에서는 해당 이모티콘이 파란색 키캡 이모티콘으로 안깨지고 이쁘게 나오는데 아래 스크린샷에서 보시다시피 업로드한 글에서는 깨져보입니다.
다만, 제목1 크기에서는 잘 나오고 목차와 본문에서 깨지는 걸 보니 '본문1,2,3?'의 크기로 나타났을 때 깨지는 것 같습니다.

**발생 과정**
버그가 어떤 과정을 통해 발생하는지 구체적으로 적어주세요.

글써서 업로드하면 목차와 본문에서 확인할 수 있습니다.

**스크린샷 및 링크**
버그가 발생한 상황을 가능하다면 스크린샷을 첨부해주세요. 또한 버그가 발생한 모습이 있는 포스트의 주소를 첨부해주시는 것도 아주 좋습니다!
![image](https://github.com/pronist/hello/assets/136432058/20ce5ca3-4d9c-48e4-b9d3-b998492e0860)

테마 너무 예뻐요. 감사합니다.

**Comment by pronist** [comment]
@ls2hn 안녕하세요. 제보해주셔서 감사합니다. 일단 확인은 되었는데, 구체적인 원인 파악은 되지 않았습니다. 가능하면 다음 패치 때 수정해보도록 하겠습니다.
