### ISSUE TITLE
모바일 스킨에서 첫 글목록 제목 위치 오류

### ISSUE THREAD

**Issue by savvy78** [pronist/hello#239]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: [e.g. windows] - 안드로이드
- 브라우저: [e.g. chrome, safari] - 엣지
- 스킨 버전 (스킨 버전은 index.xml 에서 확인): [e.g 3.4.0] - 4.6.1

**설명**
모바일 화면에서 첫 글목록 제목이 짤립니다.

**발생 과정**

**스크린샷 및 링크**
버그가 발생한 상황을 가능하다면 스크린샷을 첨부해주세요. 또한 버그가 발생한 모습이 있는 포스트의 주소를 첨부해주시는 것도 아주 좋습니다!

![스크린샷 2024-07-04 134731](https://github.com/pronist/hello/assets/67028398/341413da-a4bc-4b28-afc9-7d4241169197)

좋은 스킨 늘 감사히 잘 사용하고 있습니다.

**Comment by pronist** [comment]
@savvy78 그렇네요. 확인 완료되었습니다. 감사합니다.
