### ISSUE TITLE
라이트 모드에서 Scrollspy 목차의 색 변경이 일어나지 않음

### ISSUE THREAD

**Issue by patulus** [pronist/hello#240]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: Windows
- 브라우저: Microsoft Edge
- 버전: 126.0.2592.87
- 스킨 버전 (스킨 버전은 index.xml 에서 확인): 4.8.0

**설명**
**발생 과정**
다크 모드와 달리 라이트 모드에서 Scrollspy 목차의 색 변경이 일어나지 않고 있어요.

**스크린샷 및 링크**
![스크린샷 2024-07-10 141202](https://github.com/pronist/hello/assets/7178737/da238768-07eb-4951-b991-654ee4ed768e)|![스크린샷 2024-07-10 141209](https://github.com/pronist/hello/assets/7178737/727240e3-0fab-44ae-9024-8494c90013f0)
--- | --- |

**Comment by pronist** [comment]
@patulus 안녕하세요. 네, 맞습니다. 현재 그 버그가 확인되었습니다. 감사합니다 :)
