### ISSUE TITLE
대표이미지 없는 포스팅 이미지 문제

### ISSUE THREAD

**Issue by Cyp9715** [pronist/hello#241]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: [e.g. windows]
- 브라우저: [e.g. chrome, safari]
- 버전: [e.g. 22]
- 스킨 버전 (스킨 버전은 index.xml 에서 확인): [e.g 3.4.0]

**설명**
4.8.1 버전부터 대표 이미지가 지정되지 않은 포스팅에 아래와 같은 증상이 발생합니다.

![image](https://github.com/pronist/hello/assets/16573620/db4b8bfb-6250-4283-a3f2-a730d1c17cfa)

이게 의도된 사항인지, 버그인지는 잘 모르겠다만. 아무래도 버그일 확률이 더 높아보여 이슈 남깁니다.

**발생 과정**
버그가 어떤 과정을 통해 발생하는지 구체적으로 적어주세요.
[e.g. 테마 변경 버튼을 통해 화이트 모드로 변경시 코드 하이라이팅의 색상이 변하지 않습니다. ...]

**스크린샷 및 링크**
버그가 발생한 상황을 가능하다면 스크린샷을 첨부해주세요. 또한 버그가 발생한 모습이 있는 포스트의 주소를 첨부해주시는 것도 아주 좋습니다!

**Comment by pronist** [comment]
@Cyp9715 이번 패치로 추가된 사항입니다. 이미지가 없을 경우 갤러리, 그리드, 지그재그와 같은 형태의 글에서 레이아웃이 깨지는 문제가 있어 추가된 사항입니다. 버그는 아닙니다.

**Comment by pronist** [comment]
@Cyp9715 생각해보니 다른 글 형태와 다르게 리스트는 이미지가 없어도 딱히 깨질 일이 없긴하네요. 리스트는 풀백을 제외하고 재배포 해야겠습니다. 이 부분은 고려를 못했네요.

**Comment by pronist** [comment]
@Cyp9715 재배포 완료~
