### ISSUE TITLE
티스토리 신규 댓글 치환자 적용 시 방명록이 뜨는 현상

### ISSUE THREAD

**Issue by channnny** [pronist/hello#247]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: macOS
- 브라우저: Chrome
- 버전: Sonoma 14.5
- 스킨 버전 : hELLO 4.9.0

**설명**
1. [신규 댓글 치환자](https://notice.tistory.com/2645) 적용 안 되는 현상

**발생 과정**
1. 기존의 <s_rp> ... </s_rp> 태그를 <s_rp> [##_comment_group_##] </s_rp>로 수정
2. 댓글에 방명록이 표시됨

**스크린샷 및 링크**
<img width="581" alt="image" src="https://github.com/user-attachments/assets/49544694-b71c-4463-9813-305b92440069">
<img width="858" alt="image" src="https://github.com/user-attachments/assets/b738e91d-f6c2-47e4-81b6-ad43989e60a5">

참고 링크 남깁니다
https://dvlpr-chan-test.tistory.com/guestbook
https://dvlpr-chan-test.tistory.com/1

**Comment by pronist** [comment]
@channnny 안녕하세요. 이 문제는 [기능](https://pronist.tistory.com/5#%EA%B8%B0%EB%8A%A5-1)에서도 언급하였듯이 이 스킨에서 [기술적 문제](https://github.com/tistory/document-tistory-skin/issues/16)로 지원하지 않습니다.
