### ISSUE TITLE
preview 확인을 위한 npm run preview 시 axios import 문제

### ISSUE THREAD

**Issue by MinWook6457** [pronist/hello#251]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: [windows 10]
- 브라우저: [chrome]
- 스킨 버전 (스킨 버전은 index.xml 에서 확인): 4.9.0

**설명**
TSession ID와 Tistory URL 설정 후 
npm run preview 시 cannot use import statement outside a module 문제가 발생하여
package.json 에 type : module을 추가 하였으나 해결되지 않았습니다. 

**스크린샷 및 링크**

![image](https://github.com/user-attachments/assets/923e4d63-5e09-4257-a3db-5531f286d81c)

**Comment by pronist** [comment]
@MinWook6457 현재 이 문제에 대한 원인을 알 수 없어 이 문제는 보류합니다. 저도 윈도우를 개발환경으로 하고 있지만 정상 동작 중이기 때문에 문제에 대한 답변을 드리기가 어렵습니다. 개인 개발환경의 차이의 가능성이 제일 높습니다. Node, NPM 의 버전과 개인 설정 차이가 있을 수 있겠습니다. 

제 PC 의 Node, NPM 상태는 다음과 같습니다. 정상 동작 여부는 NPM Cache 를 제거하고 다시 설치한 이후에도 마찬가지입니다.

```
$ node -v
v16.16.0

$ npm -v
9.2.0
```
