### ISSUE TITLE
이미지 좌클릭 시 이상현상이 발생합니다.

### ISSUE THREAD

**Issue by HoKyoung-Kim** [pronist/hello#253]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: Windows 10
- 브라우저: Chrome
- 버전: 127.0.6533.120
- 스킨 버전 (스킨 버전은 index.xml 에서 확인): 4.9.0

**설명**
버그가 어떻게 발생하는지 알려주세요. 대략적인 버그의 설명을 적어주시면 됩니다.

이미지 좌클릭을 하면 url에 pidx={number} 파라미터가 붙으면서 화면 맨 아래에 전체 이미지들이 이상하게 깨져서 나타납니다. 

**발생 과정**
버그가 어떤 과정을 통해 발생하는지 구체적으로 적어주세요.
이미지 좌클릭을 하면 scripts 밑에 '__phocus__'라는 아이디를 가진 div 요소가 생기면서 이미지가 이상하게 나타나는 것 같습니다. 심지어 이 이상현상을 겪고 다른 티스토리 블로그에 가서 이미지를 클릭하면 동일한 현상이 발생합니다.

**스크린샷 및 링크**
![image](https://github.com/user-attachments/assets/2c5373d5-2b7e-4e1d-b0e1-428b6968afa6)

https://jingluv.tistory.com/7

**Comment by HoKyoung-Kim** [comment]
다른 장소로 이동해서 몇 시간 뒤에 클릭해보니 또 잘 작동하네요...다음주에 사업장으로 다시 이동해서 확인해보겠습니다.

**Comment by pronist** [comment]
@HoKyoung-Kim 안녕하세요 `phocus` 는 티스토리에서 자체 제공하는 이미지 갤러리 프로그램입니다. 최근 티스토리 쪽에서 패치를 활발하게 거듭하면서 다양한 버그를 만들어내고 있습니다. 스킨 개발자가 조절할 수 있는 부분은 아닙니다. :(

**Comment by HoKyoung-Kim** [comment]
> @HoKyoung-Kim 안녕하세요 `phocus` 는 티스토리에서 자체 제공하는 이미지 갤러리 프로그램입니다. 최근 티스토리 쪽에서 패치를 활발하게 거듭하면서 다양한 버그를 만들어내고 있습니다. 스킨 개발자가 조절할 수 있는 부분은 아닙니다. :(

**Comment by HoKyoung-Kim** [comment]
앗, 그렇군요. 알겠습니다. 감사합니다.
