### ISSUE TITLE
블로그 홈에서 사이드바를 열면 사이드바의 메뉴가 클릭되지 않는 현상이 존재합니다.

### ISSUE THREAD

**Issue by jgh05168** [pronist/hello#258]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: windows11
- 브라우저: chrome, 모바일
- 버전: 126.0.2592.87
- 스킨 버전 (스킨 버전은 index.xml 에서 확인): 4.10.0

**설명**
블로그 홈에서 사이드바를 열어 사이드바 메뉴를 클릭하는 경우, 전체 글에 있는 글이 클릭되는 현상이 발생합니다.

**발생 과정**
F12를 통해 웹 블럭을 확인해본 결과, 스크린샷과 같이 덮어씌우게 됩니다. 

**스크린샷 및 링크**
![image](https://github.com/user-attachments/assets/af2f7305-7e68-4e6b-8008-0f3db5fd947b)

블로그 링크도 남겨두겠습니다. 항상 감사드립니다 !!
realhackylife.tistory.com

**Comment by pronist** [comment]
@jgh05168 안녕하세요.

이 버그는 이미 [4.10.1](https://github.com/pronist/hello/releases/tag/4.10.1) 에서 패치되었습니다.

**Comment by jgh05168** [comment]
답변주셔서 감사합니다! 4.10.1 버전을 다운로드 받은 뒤, 스킨 편집을 진행하려고 하는데 태그 하나만 수정해도 아래 사진처럼 뿌옇게 나타납니다 ㅜㅜ 이 문제는 어떻게 해결할 수 있을까요?
![image](https://github.com/user-attachments/assets/df5e7154-3ed0-45c5-b3af-212b7b1f4873)

**Comment by pronist** [comment]
@jgh05168 다운로드를 다시 받아보시겠어요? 다운로드 링크가 4.10.1 이 아니라 4.10.0 으로 잘못되어 있었습니다.

**Comment by jgh05168** [comment]
답변 감사드립니다! 하지만 여전히 같은 문제가 발생합니다ㅜㅜ
LaTex 수식을 사용하기 위해 head에 script문 하나만 넣어도 위 사진과 같은 현상이 발생하길래 이유를 찾고자 테스트해보았는데 편집을 하는 경우에는 무조건 위 그림처럼 막히는 것 같습니다ㅜ
