### ISSUE TITLE
스킨 버전 정보 미반영 문제 - v4.10.1 적용 후 하단에 v4.10.0으로 표시됨

### ISSUE THREAD

**Issue by limehee** [pronist/hello#259]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: macOS Sequoia 15.0.1
- 브라우저: 설치된 브라우저 `Chrome`, `Safari`에서 모두 확인됨
- 버전: 4.10.1
- 스킨 버전 (스킨 버전은 index.xml 에서 확인): 4.10.1

**설명**
버전 업데이트를 v4.10.1로 적용했으나, 페이지 하단의 스킨 정보가 **hELLO · Designed By 정상우. v4.10.0**으로 여전히 표시되고 있습니다.

**발생 과정**
1. 스킨 업데이트를 v4.10.1로 적용
2. 페이지를 새로고침하여 버전 정보를 확인
3. 페이지 하단에 여전히 v4.10.0이 표시됨

**스크린샷 및 링크**
![image](https://github.com/user-attachments/assets/cfe8b634-86ff-466f-a2b4-3f374764fa90)

**Comment by pronist** [comment]
@limehee 안녕하세요.

감사합니다. 

스킨 배포 페이지 링크를 이름만 바꾸고 정작 주소는 갱신을 안 해 가지고 
4.10.0 이 다운로드 되도록 처리되어 있었네요.

ㅋㅋ; 이런 실수를;

다운로드 링크를 4.10.1 으로 바꿔놓았으니 이제 정상적으로 될 거에요.

**Comment by limehee** [comment]
빠른 피드백 반영에 감사드립니다! 지속적인 업데이트를 제공해주셔서 정말 감사드립니다. 앞으로도 응원하며 좋은 스킨 개발과 개선 기대하겠습니다. 😊
