### ISSUE TITLE
블로그 최초 진입시 무한 로딩걸리는 현상

### ISSUE THREAD

**Issue by Gilbert9172** [pronist/hello#262]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: m1 pro
- 브라우저: chrome
- 버전: 131.0.6778.109(공식 빌드) (arm64)
- 4.10.1

**설명**
- 다운로드 받은 모든 파일을 업로드 하였습니다.
- 블로그 최초 진입시 무한 로딩이 걸립니다. 
- 스킨 적용해지 하면 정상 구동하고 있습니다.

**발생 과정**
블로그 최초 진입시 무한 로딩이 걸립니다. 

**스크린샷 및 링크**
<img width="1227" alt="스크린샷 2024-12-10 오후 6 44 12" src="https://github.com/user-attachments/assets/f7702489-5359-4ee2-ac3b-c24ab624e795">
<img width="1450" alt="스크린샷 2024-12-10 오후 6 44 02" src="https://github.com/user-attachments/assets/59922098-a92e-4bd0-a383-cc84c4c37847">
https://gilbert9172.tistory.com/

**Comment by kimkeonlee** [comment]
기존의 images 폴더안에 'script.A0ejksw5AKdUaTyVnjCQ.js'  583번째 줄에서 오류가 발생하는것 같습니다.

기존코드
setTitleToEditEntryFrame: function setTitleToEditEntryFrame() {
    document.getElementById("editEntry").title = "Edit Entry";
}

윗 이슈에서 달아주셨던것 처럼 임시 주석처리하거나 기존 코드를 아래 코드로 수정하면 정상 작동 되는것 같아요!

setTitleToEditEntryFrame: function setTitleToEditEntryFrame() {
    const editEntry = document.getElementById("editEntry");
    if (editEntry) {
        editEntry.title = "Edit Entry";
    }
}

**Comment by pronist** [comment]
@Gilbert9172 안녕하세요.

문제의 코드를 날리고 4.10.2 버전을 배포하였습니다. 

확인해보시기 바랍니다.

**Comment by Gilbert9172** [comment]
@pronist 빠른 대응 감사합니다!!👍
