### ISSUE TITLE
4.10.2a 적용 후 스크립트 에러 확인 요청 드립니다.

### ISSUE THREAD

**Issue by DongJu-Na** [pronist/hello#266]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제:  windows
- 브라우저:  chrome
- 버전: 4.10.2a
- 

**설명**
최신 배포 버전을 적용 후 무한로딩.. 😂
제가 어떤 걸 놓친게 있을까요?

**발생 과정**
버그가 어떤 과정을 통해 발생하는지 구체적으로 적어주세요.
 $('.btn_etc') 객체를 못찾고 있는 것 같습니다.
 
**스크린샷 및 링크**
<img width="1086" alt="image" src="https://github.com/user-attachments/assets/82579ef5-79f8-4d7a-b9e8-bd832bddab4e">

<img width="305" alt="image" src="https://github.com/user-attachments/assets/d93531a9-f427-41df-8518-20b394295951">

https://djlife.tistory.com/

**Comment by pronist** [comment]
@DongJu-Na 안녕하세요.

hELLO 는 jQuery 를 사용하지 않을 뿐만 아니라 에러가 발생한 common.js 는 hELLO 에서 사용되지 않는 파일입니다. 또한 네트워크 탭을 보니 스크립트를 정상적으로 로드하지 못하고 있습니다. 스킨을 다시 적용하실 때 images 폴더에 있는 파일들을 정상적으로 업로드 하셨나요?

**Comment by DongJu-Na** [comment]
@pronist

헉 제가 images/ 하위 파일들을 누락해서 발생했네요.. 
급하게 적용하려다가 누락한 것 같아요 확인 감사합니다 이슈는 종료하겠습니다!!
