### ISSUE TITLE
소제목 이름이 같을 때, 목차가 생성되지 않는 문제

### ISSUE THREAD

**Issue by yonghyeonpark** [pronist/hello#267]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: 윈도우
- 브라우저: 크롬
- 버전: 4.10.2a
- 스킨 버전 (스킨 버전은 index.xml 에서 확인): [e.g 3.4.0]

**설명**
버그가 어떻게 발생하는지 알려주세요. 대략적인 버그의 설명을 적어주시면 됩니다.

**발생 과정**
버그가 어떤 과정을 통해 발생하는지 구체적으로 적어주세요.
=> 제목 이름이 같을 때, 목차가 생성되지 않는데, 혹시 의도하신 부분이라 따로 커스텀을 해야 하는 건지 버그인 건지 궁금합니다.

**스크린샷 및 링크**
![image](https://github.com/user-attachments/assets/cb9f266e-3b2d-41bf-b4c7-13b3aee27e62)

**Comment by pronist** [comment]
@yonghyeonpark 안녕하세요.

일단 이 부분은 의도된 동작이 아니기 때문에 버그로 처리하는 것이 맞겠습니다.
제보해주셔서 감사합니다. :)

**Comment by yonghyeonpark** [comment]
넵! 답변 감사드립니다~
