### ISSUE TITLE
홈화면 1100px이하에서 페이지네이션이 1로만 표시됩니다.

### ISSUE THREAD

**Issue by hynxp** [pronist/hello#268]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: mac
- 브라우저: chrome
- 버전: 4.10.2a
- 스킨 버전 (스킨 버전은 index.xml 에서 확인): [e.g 3.4.0]

**설명**
홈 화면에서 1100px이하일 때 페이지네이션이 1만 보입니다.

**발생 과정**
홈 화면에서 1100px일 때 페이지네이션이 1로만 표시되고, 늘려서 1101px이상이 되면 정상적으로 표시됩니다.

**스크린샷 및 링크**
<img width="1113" alt="image" src="https://github.com/user-attachments/assets/5d550a0f-a124-42a2-820a-390c47d3e7a1" />
<img width="1138" alt="image" src="https://github.com/user-attachments/assets/b5fcbb88-4d90-41d9-b5c7-8edd28e58ea6" />

**Comment by pronist** [comment]
@hynxp 안녕하세요.

그 부분은 스킨에서 반응형을 위한 의도된 사양이므로 버그가 아닙니다.
티스토리 페이징은 스킨 개발자가 건드릴 수 있는 자유도가 낮아서 어쩔 수 없답니다 ㅎ
