### ISSUE TITLE
방문자수 잘림

### ISSUE THREAD

**Issue by minikupa** [pronist/hELLO#38]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: 윈도우, 안드로이드
- 브라우저: 크롬, 웨일(PC, 모바일)
- 스킨 버전 : 3.4.3

**설명**
방문자 수가 100만 단위를 넘어가면 전체가 표시되지 않고, 잘립니다.

**스크린샷 및 링크**
![image](https://user-images.githubusercontent.com/19676242/128097830-f204530e-e076-472c-9d09-a7c5d5e707bf.png)

**Comment by pronist** [comment]
@minikupa 스킨을 첨 만들고 배포할 때 일반적으로 방문자 수가 100만을 넘지 않을 것이라고 상정하고 일부러 안 보이게 만든 것이긴했는데... 대단하시군요!  이 부분은 의도한 것이었지만 수정을 해야 할 시기가 왔나보네요. 처리해야겠습니다~

**Comment by pronist** [comment]
이 문제는 처리 되었음을 알립니다. 출력 범위를 조금 더 늘리기로 하였습니다. :)
