### ISSUE TITLE
[기능 요청] 본문 내 빈 줄 사라짐 현상

### ISSUE THREAD

**Issue by TetraTheta** [pronist/hELLO#41]
# 환경

- 운영체제: Windows 11
- 브라우저: Edge (Chromium)
- 버전: 94.0.992.50
- 스킨 버전: 3.4.4

# 설명
스킨 자체의 버그라기보다는 티스토리의 강제적인 정책 때문인 것으로 추측됩니다만, 본문 내의 빈 줄의 스타일에 전부 `display: none !important`가 추가됩니다.
```html
<p data-ke-size="size16" style="display: none !important;">&nbsp;</p>
```
이렇게요. 문제는 이걸 끌 수 있는 기능을 티스토리가 제공하고 있지 않기에, 빈 줄을 다시 보여주기 위해서는 스킨의 힘을 빌어야 하는 상황입니다.

현재 최신 버전인 3.4.5보다 버전이 낮지만, 커밋 기록을 보았을 때 3.4.5에서 이 문제가 해결된 것 같지 않아보입니다.

# 발생 과정
글을 작성 시 빈 줄을 일반 줄 사이사이에 넣은 후, 글을 발행합니다. 발행된 글에서 빈줄이 사라진 것을 확인합니다.

# 스크린샷
![real](https://user-images.githubusercontent.com/37061801/137757360-636224d8-6030-4e72-a6e2-1af68883595b.png)

![f12](https://user-images.githubusercontent.com/37061801/137757379-f630cf38-9bac-41d4-8d2f-9892ab8abc92.png)

![source](https://user-images.githubusercontent.com/37061801/137757526-df2c8939-517c-4a03-83b9-1bd5fb3c1ed5.png)

각각 실제 표시되는 모습, F12 개발자 모드로 본 HTML 코드, 페이지 소스 보기로 본 본문 내용입니다.

**Comment by pronist** [comment]
@TetraTheta 흠, 버그 상황을 재현하고 싶은데 글을 작성하실 때 어떤 방법으로 하시는지 정확히 알 수가 없어 의문입니다. 기본적인 티스토리 에디터에서 글을 처음부터 작성하지 않고 **복사/붙여넣기** 사용하지 않는 한, 그런 증상이 발생하는 일은 많이 없는 것으로 알고 있습니다. 타 홈페이지의 글을 에디터에 복사/붙여넣기하는 경우 티스토리 에디터에서 처리를 어떻게 할 지는 경우의 수가 많아 짐작하기 어려운 경우가 많답니다.

또한 스킨에서 자체적으로 티스토리 에디터에서 동작하는 부분을 스킨에서 통제하는 패치는 추구하고자 하는 방향이 아니라 명확한 버그가 아니라면 패치가 진행되지 않을 것입니다.
