### ISSUE TITLE
게시글 하단 소셜 아이콘 포지션 흐트러짐

### ISSUE THREAD

**Issue by 960813** [pronist/hELLO#43]
**환경 (버그가 발생한 환경을 적어주세요.):**

- 운영체제: iOS
- 브라우저: Firefox Daylight 39.0(6519) / MacOS Safari iPhone 모드
- 스킨 버전 (스킨 버전은 index.xml 에서 확인): 3.4.5

**설명**
게시글 본문 하단 소셜 아이콘의 위치가 정상적으로 정렬되지 않습니다.

**발생 과정**
iOS Firefox Daylight 브라우저 / MacOS Safari 브라우저 Development -> UserAgent -> Safari iPhone

두 환경에서 아이콘이 왼쪽으로 쏠리는 현상이 있습니다.

**스크린샷 및 링크**
MacOS Safari
<img width="713" alt="Screen Shot 2021-11-11 at 12 18 20 PM" src="https://user-images.githubusercontent.com/44586666/141231336-8ae25c00-af08-4ed1-b5fa-b80931dc9049.png">

iOS Firefox
![IMG_5469](https://user-images.githubusercontent.com/44586666/141231352-36e6a7a5-7e92-4f33-b685-28a5177b4914.PNG)

**Comment by pronist** [comment]
@960813 정말. 원인불명이랍니다. 이 버그는 쭉 알고 있었기는 하지만, 저도 아이폰 사파리에선 같은 증상이 발생하고 있습니다만, 웃기는 사실은 IOS Safari 의 하단 메뉴가 올라갔다 내려갔다 하면 저 버그도 들쭉날쭉 하다는 겁니다. 저도 프론트엔드 개발자는 아닌지라, 참 그렇긴하지만 답답하기 그지없답니다. ㅜㅜ

그래서 결론: 아직 못 고침. 정확히는 언제 고칠지 모르겠군요.

**Comment by pronist** [comment]
@960813 이 문제는 표현 방식을 바꾸어 해결이 되었음을 알립니다!
