### ISSUE TITLE
파일 다운로드 버튼 색상 문제

### ISSUE THREAD

**Issue by CodeName393** [pronist/hELLO#5]
[https://codename393.tistory.com/1](url)
이 게시물 밑 '다운로드' 항목을 보시면 다운로드 아이콘 색상이 변경이 안되 잘 안보입니다.
![캡처](https://user-images.githubusercontent.com/62503817/89746364-2cfee880-daf4-11ea-80c8-0b1db535a7fc.PNG)

**Comment by pronist** [comment]
기여해주셔서 감사합니다! 해당 스타일의 문제는 **해결**되었습니다.
