### ISSUE TITLE
라이트 모드 다크모드 전환 버튼 오류

### ISSUE THREAD

**Issue by CodeName393** [pronist/hELLO#8]
![캡처](https://user-images.githubusercontent.com/62503817/89852405-b8967900-dbc9-11ea-8832-a8280db65d68.PNG)
사진과 같이 텍스트가 겹쳐 나올때 전환이 안되며 페이지를 새로고침해야지 해결됩니다.
또한 이 증상이 너무 자주 발생합니다.

**Comment by pronist** [comment]
단순히 사진으로만 봐서는 저 현상이 발생하는 **조건**과 상황적 특성을 알 수 없습니다. 
**조금 더 자세한 설명**이 필요합니다.

테마 버튼에 대한 것을 조절하는 행위는 로컬스토리지를 사용합니다.
혹여나 로컬스토리지가 조작되었거나, 브라우저가 로컬 스토리지를 지원하지 않는 경우에 그럴 수 있습니다.
조금 더 자세한 이야기 부탁드립니다.

**Comment by CodeName393** [comment]
> 단순히 사진으로만 봐서는 저 현상이 발생하는 **조건**과 상황적 특성을 알 수 없습니다.
> **조금 더 자세한 설명**이 필요합니다.
> 
> 테마 버튼에 대한 것을 조절하는 행위는 **로컬 스토리지**를 사용합니다.
> 혹여나 로컬 스토리지가 조작되었거나, 브라우저가 로컬 스토리지를 지원하지 않는 경우에 그럴 수 있습니다.
> 
> 어떤 브라우저에서, 어떤 행위를 하면 저런 현상이 발생하는지 조금 더 자세한 이야기 부탁드립니다.

원인을 찾은거 같습니다.
**라이트 모드로 보기** 또는 **다크 모드로 보기** 글자를 드래그한 상태에서 버튼을 누르면 드래그된 글자가 유지되면서 변화헌 텍스트까지 같이 겹치는 거 같습니다.

**Comment by pronist** [comment]
크롬, 웨일, 파이어 폭스의 최신버전 기준에서 그 버그는 찾지 못했습니다. 어떤 브라우저를 사용하고 계신가요?

**Comment by CodeName393** [comment]
> **크롬, 웨일, 파이어폭스**의 최신버전 기준에서 그 버그는 찾지 못했습니다.
> 어떤 브라우저를 사용하고 계신가요?

크롬 사용중입니다.
그러고 보니 티스토리 플러그인 중에 우클릭 방치 플러그인이 있는데 적용을 해도 적용이 되지 않습니다. 이거와 관련이 있을까요?

**Comment by pronist** [comment]
@CodeName393 우클릭 방지 플러그인은 일단 저도 사용 중이긴 한데 .. 아직까지는 버그가 발생하는 조건을 모르겠는지라 명확하게 해결할 수는 없을 것같네요. 설령, 원인을 안다고 해도 스킨자체의 문제는 아닐 수도 있으니 .. 우선, 이슈는 이대로 놔두도록 하겠습니다.

**Comment by pronist** [comment]
차기 버전에서 동작방식을 일부 바꾸어 이 문제를 해결합니다.
기여해주셔서 감사합니다!
