### ISSUE TITLE
코드블럭 폰트 변경 건의 + 오류

### ISSUE THREAD

**Issue by jhhan128** [pronist/hELLO#9]
코드블럭 폰트가 일반 고딕체로 나옵니다.
이를 고정폭 글꼴로 바꾸는 것은 어떨까요?

한번 제안드려봅니다.

또한 제가 html에서 건드린 게 없음에도 Designed by...  가 나오지 않습니다. 
이것도 버그인 것 같네요.

**Comment by pronist** [comment]
1. **코드블럭**은 에디터 상에서 복사 붙여넣기를 한다거나 그와 비슷한 행동을 한 경우 에디터 내에서 **인라인 style** 을 적용하므로 스타일이 강제로 변경됩니다.
2. 가로 사이즈 **1600px** 이하에서는 designed by 가 출력되지 않습니다.

**Comment by pronist** [comment]
@jhhan128 코드블럭 폰트를 고정폭 글꼴인 **D2Coding** 으로 바꾸었습니다. 
건의해주셔서 감사합니다!
